name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches_ignore: []

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      
      - name: Setup environment
        run: conda env create --quiet --name eresearch --file tests/test-environment.yml

      - name: Run tests
        env:
          CI: true
        run: |
          export PATH="/usr/share/miniconda/bin:$PATH"
          source activate eresearch
          pytest tests/test*.py -v -x
